/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistempenjualan;

import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author nurhalizah
 */
public class FormPenjualan extends javax.swing.JPanel {

    private Bootstrap app;

    // Constants for table column indices
    private static final int COL_ID_PRODUK = 0;
    private static final int COL_KODE_PRODUK = 1;
    private static final int COL_NAMA_PRODUK = 2;
    private static final int COL_HARGA = 3;
    private static final int COL_JUMLAH = 4;
    private static final int COL_SUBTOTAL = 5;
    private static final int COL_AKSI = 6;

    // Components
    private JTextField txtNoTransaksi;
    private JTextField txtTanggal;
    private JComboBox<String> cmbPelanggan;
    private JTextField txtNamaPelanggan;
    private JTextField txtNoHp;
    private JButton btnAddPelanggan;
    private JButton btnTambahProduk;
    private JTable tblProduk;
    private DefaultTableModel modelProduk;
    private JTextField txtSubtotal;
    private JTextField txtGrandTotal;
    private JButton btnTambahTransaksi;

    // Tambahan field untuk GUEST
    private JRadioButton rbLakiLaki;
    private JRadioButton rbPerempuan;
    private ButtonGroup bgJenisKelamin;
    private JTextArea txtAddress;
    private JLabel lblJenisKelamin;
    private JLabel lblAddress;
    private JPanel panelJenisKelamin;
    private JScrollPane scrollAddress;

    private Connection conn;
    private int selectedCustomerId = 0;
    private String selectedGender = "";

    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan(Bootstrap app) {
        this.app = app;
        init();
    }

//    @Override
//    public void setVisible(boolean visible) {
//        super.setVisible(visible);
//        if (visible) {
//            init();
//        }
//    }

    private void init() {
        initComponents();
        setupCustomComponents();
        setupDatabase();
        generateNoTransaksi();
        setTanggalOtomatis();
        loadCustomers();
        setupTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("No Transaksi");

        jLabel2.setText("Tanggal Transaksi");

        jLabel3.setText("Pelanggan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Produk"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Tambah Produk");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Subtotal ");

        jTextField3.setActionCommand("<Not Set>");
        jTextField3.setRequestFocusEnabled(false);

        jButton3.setText("Tambah Transaksi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pelanggan"));

        jLabel5.setText("Nama ");

        jLabel6.setText("No Hp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(153, 153, 153)
                        .addComponent(jTextField3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(354, 354, 354)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox1, 0, 251, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(56, 56, 56)
                .addComponent(jButton3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("Form Transaksi");

        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Pilih Produk", true);
        dialog.setSize(550, 400);
        dialog.setLocationRelativeTo(this);

        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Model tabel: ID, Kode, Nama Produk, Harga, Stok
        DefaultTableModel modelProduk = new DefaultTableModel(
                new Object[]{"ID", "Kode", "Nama Produk", "Harga", "Stok"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        JTable tblProduk = new JTable(modelProduk);

        // Sembunyikan kolom ID
        tblProduk.getColumnModel().getColumn(0).setMinWidth(0);
        tblProduk.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProduk.getColumnModel().getColumn(0).setPreferredWidth(0);
        // Lebar kolom lain
        tblProduk.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblProduk.getColumnModel().getColumn(2).setPreferredWidth(180);
        tblProduk.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblProduk.getColumnModel().getColumn(4).setPreferredWidth(60);

        JScrollPane scroll = new JScrollPane(tblProduk);

        // Load produk dengan stok dari database
        Map<Integer, Integer> stockMap = new HashMap<>();
        try {
            String query = "SELECT p.id, p.code, p.product_name, p.price, COALESCE(s.stock, 0) AS stock "
                    + "FROM m_product p LEFT JOIN stock s ON p.id = s.product_id ORDER BY p.product_name";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                int id = rs.getInt("id");
                int stock = rs.getInt("stock");
                modelProduk.addRow(new Object[]{
                    id,
                    rs.getString("code"),
                    rs.getString("product_name"),
                    rs.getDouble("price"),
                    stock
                });
                stockMap.put(id, stock);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading produk: " + e.getMessage());
        }

        JButton btnPilih = new JButton("Pilih");
        btnPilih.setEnabled(false); // akan diaktifkan setelah ada baris terpilih dengan stok > 0

        // Listener untuk mengaktifkan tombol hanya jika baris dipilih dan stok > 0
        tblProduk.getSelectionModel().addListSelectionListener(e -> {
            int selectedRow = tblProduk.getSelectedRow();
            if (selectedRow >= 0) {
                int stok = (int) modelProduk.getValueAt(selectedRow, 4);
                btnPilih.setEnabled(stok > 0);
            } else {
                btnPilih.setEnabled(false);
            }
        });

        btnPilih.addActionListener(e -> {
            int selectedRow = tblProduk.getSelectedRow();
            if (selectedRow >= 0) {
                int id = (int) modelProduk.getValueAt(selectedRow, 0);
                String kode = (String) modelProduk.getValueAt(selectedRow, 1);
                String nama = (String) modelProduk.getValueAt(selectedRow, 2);
                double harga = (double) modelProduk.getValueAt(selectedRow, 3);
                int stok = (int) modelProduk.getValueAt(selectedRow, 4);

                // Periksa stok (seharusnya sudah >0 karena tombol hanya aktif jika stok>0)
                if (stok <= 0) {
                    JOptionPane.showMessageDialog(dialog, "Stok produk ini habis!", "Stok Habis", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // Tambahkan ke tabel transaksi (qty default 1)
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                boolean produkSudahAda = false;
                for (int i = 0; i < model.getRowCount(); i++) {
                    int idDiTable = (int) model.getValueAt(i, COL_ID_PRODUK);
                    if (idDiTable == id) {
                        int qtyLama = Integer.parseInt(model.getValueAt(i, COL_JUMLAH).toString());
                        int qtyBaru = qtyLama + 1;

                        // Cek apakah melebihi stok
                        if (qtyBaru > stok) {
                            JOptionPane.showMessageDialog(dialog,
                                    "Stok tidak mencukupi! Stok tersedia: " + stok,
                                    "Stok Tidak Cukup", JOptionPane.WARNING_MESSAGE);
                            return;
                        }

                        model.setValueAt(qtyBaru, i, COL_JUMLAH);
                        double subtotalBaru = harga * qtyBaru;
                        model.setValueAt(subtotalBaru, i, COL_SUBTOTAL);
                        produkSudahAda = true;
                        break;
                    }
                }

                if (!produkSudahAda) {
                    model.addRow(new Object[]{
                        id, kode, nama, harga, 1, harga, "Hapus"
                    });
                }

                hitungGrandTotal();
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog, "Pilih produk terlebih dahulu!");
            }
        });

        panel.add(scroll, BorderLayout.CENTER);
        panel.add(btnPilih, BorderLayout.SOUTH);

        dialog.add(panel);
        dialog.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (selectedCustomerId == 0 && !jComboBox1.getSelectedItem().equals("GUEST")) {
            JOptionPane.showMessageDialog(this, "Pilih pelanggan terlebih dahulu!");
            return;
        }

        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tambahkan produk terlebih dahulu!");
            return;
        }

        try {
            conn.setAutoCommit(false);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            double grandTotal = 0;

            // Validasi stok untuk setiap item
            for (int i = 0; i < model.getRowCount(); i++) {
                int productId = (int) model.getValueAt(i, COL_ID_PRODUK);
                int qty = Integer.parseInt(model.getValueAt(i, COL_JUMLAH).toString());
                int stok = getStock(productId);

                if (qty > stok) {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this,
                            "Stok tidak mencukupi untuk produk: " + model.getValueAt(i, COL_NAMA_PRODUK)
                            + "\nStok tersedia: " + stok + ", diminta: " + qty,
                            "Stok Tidak Cukup", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Insert transaksi header
            String queryTransaksi = "INSERT INTO trx (trx_number, created_at, sales_id, customer_id, grand_total) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pstmtTransaksi = conn.prepareStatement(queryTransaksi, Statement.RETURN_GENERATED_KEYS);
            pstmtTransaksi.setString(1, jTextField1.getText());
            pstmtTransaksi.setString(2, jTextField2.getText());
            pstmtTransaksi.setInt(3, this.app.getSessionUserId());
            pstmtTransaksi.setInt(4, selectedCustomerId);

            // Hitung grand total ulang dengan aman
            for (int i = 0; i < model.getRowCount(); i++) {
                Object subtotalObj = model.getValueAt(i, COL_SUBTOTAL);
                if (subtotalObj instanceof Number) {
                    grandTotal += ((Number) subtotalObj).doubleValue();
                }
            }
            pstmtTransaksi.setDouble(5, grandTotal);
            pstmtTransaksi.executeUpdate();

            ResultSet rs = pstmtTransaksi.getGeneratedKeys();
            int idTransaksi = 0;
            if (rs.next()) {
                idTransaksi = rs.getInt(1);
            }

            // Insert detail transaksi dan update stok
            String queryDetail = "INSERT INTO trx_detail (trx_id, product_id, qty, subprice, price) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pstmtDetail = conn.prepareStatement(queryDetail);
            String updateStok = "UPDATE stock SET stock = stock - ? WHERE product_id = ?";

            for (int i = 0; i < model.getRowCount(); i++) {
                int productId = (int) model.getValueAt(i, COL_ID_PRODUK);
                int qty = Integer.parseInt(model.getValueAt(i, COL_JUMLAH).toString());

                Object hargaObj = model.getValueAt(i, COL_HARGA);
                Object subtotalObj = model.getValueAt(i, COL_SUBTOTAL);
                double harga = hargaObj instanceof Number ? ((Number) hargaObj).doubleValue() : 0;
                double subtotal = subtotalObj instanceof Number ? ((Number) subtotalObj).doubleValue() : 0;

                pstmtDetail.setInt(1, idTransaksi);
                pstmtDetail.setInt(2, productId);
                pstmtDetail.setInt(3, qty);
                pstmtDetail.setDouble(4, harga);      // subprice = harga satuan
                pstmtDetail.setDouble(5, subtotal);   // price = total harga (qty * harga)
                pstmtDetail.executeUpdate();

                // Update stok
                PreparedStatement pstmtStok = conn.prepareStatement(updateStok);
                pstmtStok.setInt(1, qty);
                pstmtStok.setInt(2, productId);
                pstmtStok.executeUpdate();
            }

            conn.commit();
            tampilkanRincianTransaksi(idTransaksi, jTextField1.getText(), grandTotal);

            // Reset form
            resetForm();

        } catch (SQLException e) {
            try {
                conn.rollback();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Error menyimpan transaksi: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                conn.setAutoCommit(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private int getStock(int productId) throws SQLException {
        String sql = "SELECT COALESCE(stock, 0) AS stock FROM stock WHERE product_id = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, productId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt("stock");
            }
        }
        return 0;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        app.showDashboard();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setupCustomComponents() {
        jTextField1.setEditable(false);  // No Transaksi
        jTextField2.setEditable(false);  // Tanggal
        jTextField3.setEditable(false);  // Subtotal

        jTextField4.setEditable(false);  // Nama Pelanggan
        jTextField5.setEditable(false);  // No HP

        lblJenisKelamin = new JLabel("Jenis Kelamin");
        lblAddress = new JLabel("Alamat");

        rbLakiLaki = new JRadioButton("Laki-laki");
        rbPerempuan = new JRadioButton("Perempuan");
        bgJenisKelamin = new ButtonGroup();
        bgJenisKelamin.add(rbLakiLaki);
        bgJenisKelamin.add(rbPerempuan);

        panelJenisKelamin = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 0));
        panelJenisKelamin.add(rbLakiLaki);
        panelJenisKelamin.add(rbPerempuan);

        txtAddress = new JTextArea(2, 20);
        txtAddress.setLineWrap(true);
        txtAddress.setWrapStyleWord(true);
        scrollAddress = new JScrollPane(txtAddress);

        // Sembunyikan dulu field tambahan
        lblJenisKelamin.setVisible(false);
        lblAddress.setVisible(false);
        panelJenisKelamin.setVisible(false);
        scrollAddress.setVisible(false);

        jComboBox1.addActionListener(e -> onPelangganSelected());
    }

    private void setupDatabase() {
        try {
            conn = Koneksi.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi database gagal: " + e.getMessage());
        }
    }

    private void generateNoTransaksi() {
        try {
            String today = new SimpleDateFormat("yyyyMMdd").format(new Date());
            String query = "SELECT MAX(CAST(SUBSTRING(trx_number, 14) AS UNSIGNED)) AS max_no "
                    + "FROM trx WHERE trx_number LIKE 'TRX-" + today + "-%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            int nextNo = 1;
            if (rs.next() && rs.getInt("max_no") > 0) {
                nextNo = rs.getInt("max_no") + 1;
            }
            jTextField1.setText(String.format("TRX-%s-%03d", today, nextNo));
        } catch (SQLException e) {
            String today = new SimpleDateFormat("yyyyMMdd").format(new Date());
            jTextField1.setText("TRX-" + today + "-001");
        }
    }

    private void setTanggalOtomatis() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        jTextField2.setText(sdf.format(new Date()));
    }

    private void loadCustomers() {
        try {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("-- Pilih Pelanggan --");
            jComboBox1.addItem("GUEST");

            String query = "SELECT id, customer_name FROM m_customer ORDER BY customer_name";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                jComboBox1.addItem(rs.getInt("id") + " - " + rs.getString("customer_name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
        }
    }

    private void onPelangganSelected() {
        String selected = (String) jComboBox1.getSelectedItem();
        if (selected == null || selected.equals("-- Pilih Pelanggan --")) {
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField4.setEditable(false);
            jTextField5.setEditable(false);
            removeAddButton();
            hideGuestFields();
            selectedCustomerId = 0;
            return;
        }

        if (selected.equals("GUEST")) {
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField4.setEditable(true);
            jTextField5.setEditable(true);
            txtAddress.setText("");
            bgJenisKelamin.clearSelection();
            selectedCustomerId = 0;
            showGuestFields();
            addCustomerButton();
        } else {
            try {
                String[] parts = selected.split(" - ");
                int customerId = Integer.parseInt(parts[0]);
                selectedCustomerId = customerId;

                String query = "SELECT * FROM m_customer WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setInt(1, customerId);
                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    jTextField4.setText(rs.getString("customer_name"));
                    jTextField5.setText(rs.getString("phone_number"));
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(false);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
            removeAddButton();
            hideGuestFields();
        }
    }

    private void showGuestFields() {
        lblJenisKelamin.setVisible(true);
        panelJenisKelamin.setVisible(true);
        lblAddress.setVisible(true);
        scrollAddress.setVisible(true);
    }

    private void hideGuestFields() {
        lblJenisKelamin.setVisible(false);
        panelJenisKelamin.setVisible(false);
        lblAddress.setVisible(false);
        scrollAddress.setVisible(false);
    }

    private void addCustomerButton() {
        removeAddButton();
        JButton btnAdd = new JButton("Tambah Customer");
        btnAdd.setName("btnAddCustomer");
        btnAdd.addActionListener(e -> tambahCustomerBaru());

        // Pengaturan layout dinamis untuk menampilkan field GUEST dan tombol
        GroupLayout layout = (GroupLayout) jPanel3.getLayout();
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(lblJenisKelamin)
                                        .addComponent(lblAddress))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField4, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(jTextField5, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(panelJenisKelamin, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(scrollAddress, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(btnAdd, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblJenisKelamin)
                                        .addComponent(panelJenisKelamin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAddress)
                                        .addComponent(scrollAddress, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdd)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3.revalidate();
        jPanel3.repaint();
    }

    private void removeAddButton() {
        Component[] components = jPanel3.getComponents();
        for (Component comp : components) {
            if (comp instanceof JButton && "btnAddCustomer".equals(comp.getName())) {
                jPanel3.remove(comp);
                // Kembalikan layout ke semula
                GroupLayout layout = (GroupLayout) jPanel3.getLayout();
                layout.setHorizontalGroup(
                        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel5)
                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(19, Short.MAX_VALUE))
                );
                jPanel3.revalidate();
                jPanel3.repaint();
                break;
            }
        }
    }

    private void tambahCustomerBaru() {
        String nama = jTextField4.getText().trim();
        String noHp = jTextField5.getText().trim();
        String address = txtAddress.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama harus diisi!");
            return;
        }
        if (!rbLakiLaki.isSelected() && !rbPerempuan.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jenis Kelamin harus dipilih!");
            return;
        }
        selectedGender = rbLakiLaki.isSelected() ? "L" : "P";

        try {
            String query = "INSERT INTO m_customer (customer_name, phone_number, gender, address) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            pstmt.setString(1, nama);
            pstmt.setString(2, noHp.isEmpty() ? null : noHp);
            pstmt.setString(3, selectedGender);
            pstmt.setString(4, address.isEmpty() ? null : address);
            pstmt.executeUpdate();

            ResultSet rs = pstmt.getGeneratedKeys();
            if (rs.next()) {
                selectedCustomerId = rs.getInt(1);
            }
            JOptionPane.showMessageDialog(this, "Customer berhasil ditambahkan!");
            loadCustomers();
            jComboBox1.setSelectedItem(selectedCustomerId + " - " + nama);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error menambah customer: " + e.getMessage());
        }
    }

    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID Produk", "Kode Produk", "Nama Produk", "Harga", "Jumlah", "Subtotal", "Aksi"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == COL_JUMLAH || column == COL_AKSI;
            }

            @Override
            public void setValueAt(Object aValue, int row, int column) {
                // Validasi khusus untuk kolom Jumlah
                if (column == COL_JUMLAH) {
                    try {
                        int qtyBaru = Integer.parseInt(aValue.toString());
                        if (qtyBaru <= 0) {
                            JOptionPane.showMessageDialog(FormPenjualan.this,
                                    "Jumlah harus lebih dari 0!", "Error", JOptionPane.ERROR_MESSAGE);
                            return; // batal set nilai
                        }

                        // Ambil ID produk dan stok terkini
                        int productId = (int) getValueAt(row, COL_ID_PRODUK);
                        int stok = getStock(productId); // tangani SQLException di sini

                        if (qtyBaru > stok) {
                            JOptionPane.showMessageDialog(FormPenjualan.this,
                                    "Stok tidak mencukupi!\nStok tersedia: " + stok,
                                    "Stok Tidak Cukup", JOptionPane.WARNING_MESSAGE);
                            return; // batal set nilai
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(FormPenjualan.this,
                                "Masukkan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(FormPenjualan.this,
                                "Gagal memeriksa stok: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                // Jika validasi lolos, set nilai sebenarnya
                super.setValueAt(aValue, row, column);
            }
        };

        jTable1.setModel(model);

        // Sembunyikan kolom ID Produk
        jTable1.getColumnModel().getColumn(COL_ID_PRODUK).setMinWidth(0);
        jTable1.getColumnModel().getColumn(COL_ID_PRODUK).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(COL_ID_PRODUK).setPreferredWidth(0);

        jTable1.getColumnModel().getColumn(COL_KODE_PRODUK).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(COL_NAMA_PRODUK).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(COL_HARGA).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(COL_JUMLAH).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(COL_SUBTOTAL).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(COL_AKSI).setPreferredWidth(80);

        // Renderer format Rupiah
        TableCellRenderer rupiahRenderer = (table, value, isSelected, hasFocus, row, column) -> {
            JLabel label = new JLabel();
            if (value instanceof Number) {
                label.setText(String.format("Rp %,.2f", ((Number) value).doubleValue()));
            } else {
                label.setText(value != null ? value.toString() : "");
            }
            label.setOpaque(true);
            if (isSelected) {
                label.setBackground(table.getSelectionBackground());
                label.setForeground(table.getSelectionForeground());
            } else {
                label.setBackground(table.getBackground());
                label.setForeground(table.getForeground());
            }
            label.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
            return label;
        };
        jTable1.getColumnModel().getColumn(COL_HARGA).setCellRenderer(rupiahRenderer);
        jTable1.getColumnModel().getColumn(COL_SUBTOTAL).setCellRenderer(rupiahRenderer);

        // Renderer tombol Hapus
        jTable1.getColumn("Aksi").setCellRenderer((table, value, isSelected, hasFocus, row, column) -> {
            JButton btnHapus = new JButton("Hapus");
            btnHapus.setFocusPainted(false);
            return btnHapus;
        });

        // Editor tombol Hapus
        jTable1.getColumn("Aksi").setCellEditor(new DefaultCellEditor(new JCheckBox()) {
            private JButton button;
            private int currentRow;

            {
                button = new JButton("Hapus");
                button.setFocusPainted(false);
                button.addActionListener(e -> {
                    fireEditingStopped();
                    hapusProdukDariTable(currentRow);
                });
            }

            @Override
            public Component getTableCellEditorComponent(JTable table, Object value,
                    boolean isSelected, int row, int column) {
                currentRow = row;
                return button;
            }

            @Override
            public Object getCellEditorValue() {
                return "Hapus";
            }
        });

        // Listener untuk update subtotal & grand total
        model.addTableModelListener(e -> {
            if (e.getColumn() == COL_JUMLAH) {
                int row = e.getFirstRow();
                updateRowSubtotal(row);
                hitungGrandTotal();
            }
        });
    }

    private void hapusProdukDariTable(int row) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (row >= 0 && row < model.getRowCount()) {
            model.removeRow(row);
            hitungGrandTotal();
        }
    }

    private void updateRowSubtotal(int row) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (row >= 0 && row < model.getRowCount()) {
            double harga = (double) model.getValueAt(row, COL_HARGA);
            int jumlah = Integer.parseInt(model.getValueAt(row, COL_JUMLAH).toString());
            double subtotal = harga * jumlah;
            model.setValueAt(subtotal, row, COL_SUBTOTAL);
        }
    }

    private void hitungGrandTotal() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        double total = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            total += (double) model.getValueAt(i, COL_SUBTOTAL);
        }
        jTextField3.setText(String.format("Rp %.2f", total));
    }

    private void resetForm() {
        generateNoTransaksi();
        setTanggalOtomatis();
        jComboBox1.setSelectedIndex(0);
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField3.setText("");
        txtAddress.setText("");
        bgJenisKelamin.clearSelection();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        selectedCustomerId = 0;
        hideGuestFields();
    }

    private void tampilkanRincianTransaksi(int idTransaksi, String noTransaksi, double grandTotal) {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Rincian Transaksi", true);
        dialog.setSize(500, 600);
        dialog.setLocationRelativeTo(this);

        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Header informasi
        JPanel headerPanel = new JPanel(new GridLayout(0, 1, 5, 5));
        headerPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder("Informasi Transaksi"),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)));

        JLabel lblSuccess = new JLabel("✓ Transaksi Berhasil Disimpan!");
        lblSuccess.setFont(new Font("Arial", Font.BOLD, 16));
        lblSuccess.setForeground(new Color(0, 150, 0));
        headerPanel.add(lblSuccess);
        headerPanel.add(new JLabel("No Transaksi: " + noTransaksi));
        headerPanel.add(new JLabel("Tanggal: " + jTextField2.getText()));
        headerPanel.add(new JLabel("Pelanggan: " + jTextField4.getText()));
        if (!jTextField5.getText().trim().isEmpty()) {
            headerPanel.add(new JLabel("No HP: " + jTextField5.getText()));
        }

        // Tabel detail produk
        JPanel productPanel = new JPanel(new BorderLayout(5, 5));
        productPanel.setBorder(BorderFactory.createTitledBorder("Detail Produk"));

        String[] columns = {"Produk", "Harga", "Qty", "Subtotal"};
        DefaultTableModel modelRincian = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        JTable tblRincian = new JTable(modelRincian);
        tblRincian.setRowHeight(25);

        TableCellRenderer rupiahRenderer = (table, value, isSelected, hasFocus, row, column) -> {
            JLabel label = new JLabel();
            if (value instanceof Number) {
                label.setText(String.format("Rp %,.0f", ((Number) value).doubleValue()));
            } else {
                label.setText(value != null ? value.toString() : "");
            }
            label.setOpaque(true);
            label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
            label.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
            label.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
            return label;
        };
        tblRincian.getColumnModel().getColumn(1).setCellRenderer(rupiahRenderer); // Harga
        tblRincian.getColumnModel().getColumn(3).setCellRenderer(rupiahRenderer); // Subtotal

        tblRincian.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblRincian.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblRincian.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblRincian.getColumnModel().getColumn(3).setPreferredWidth(100);

        DefaultTableModel modelTransaksi = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < modelTransaksi.getRowCount(); i++) {
            String namaProduk = (String) modelTransaksi.getValueAt(i, COL_NAMA_PRODUK);
            Object hargaObj = modelTransaksi.getValueAt(i, COL_HARGA);
            int qty = Integer.parseInt(modelTransaksi.getValueAt(i, COL_JUMLAH).toString());
            Object subtotalObj = modelTransaksi.getValueAt(i, COL_SUBTOTAL);
            double harga = hargaObj instanceof Number ? ((Number) hargaObj).doubleValue() : 0;
            double subtotal = subtotalObj instanceof Number ? ((Number) subtotalObj).doubleValue() : 0;
            modelRincian.addRow(new Object[]{namaProduk, harga, qty, subtotal});
        }

        JScrollPane scrollPane = new JScrollPane(tblRincian);
        productPanel.add(scrollPane, BorderLayout.CENTER);

        // Panel total
        JPanel totalPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        totalPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel lblGrandTotalLabel = new JLabel("GRAND TOTAL:");
        lblGrandTotalLabel.setFont(new Font("Arial", Font.BOLD, 16));
        JLabel lblGrandTotal = new JLabel(String.format("Rp %,.0f", grandTotal));
        lblGrandTotal.setFont(new Font("Arial", Font.BOLD, 16));
        lblGrandTotal.setForeground(new Color(0, 100, 200));

        totalPanel.add(new JLabel(""));
        totalPanel.add(new JLabel(""));
        totalPanel.add(lblGrandTotalLabel);
        totalPanel.add(lblGrandTotal);

        // Tombol aksi
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        JButton btnCetak = new JButton("Cetak Struk");
        btnCetak.setPreferredSize(new Dimension(120, 35));
        btnCetak.addActionListener(e -> JOptionPane.showMessageDialog(dialog, "Fitur cetak akan segera hadir!"));

        JButton btnOk = new JButton("OK");
        btnOk.setPreferredSize(new Dimension(120, 35));
        btnOk.addActionListener(e -> dialog.dispose());

        buttonPanel.add(btnCetak);
        buttonPanel.add(btnOk);

        JPanel contentPanel = new JPanel(new BorderLayout(10, 10));
        contentPanel.add(headerPanel, BorderLayout.NORTH);
        contentPanel.add(productPanel, BorderLayout.CENTER);
        contentPanel.add(totalPanel, BorderLayout.SOUTH);

        mainPanel.add(contentPanel, BorderLayout.CENTER);
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);

        dialog.add(mainPanel);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
