/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempenjualan;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import java.sql.*;
/**
 *
 * @author Hida
 */
public class MonitorStok extends javax.swing.JFrame {
    ResultSet rs;

    /**
     * Creates new form MonitorStok
     */
    public MonitorStok() {
        initComponents();
        Koneksi.koneksi();
        loadCardData();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void loadCardData() {
        try {
            String query = "SELECT " +
                "SUM(CASE WHEN stock <= 0 THEN 1 ELSE 0 END) AS habis, " +
                "SUM(CASE WHEN stock > 0 AND stock <= min_stock THEN 1 ELSE 0 END) AS menipis, " +
                "SUM(CASE WHEN stock > min_stock THEN 1 ELSE 0 END) AS tersedia " +
                "FROM stock";

            rs = Koneksi.stm.executeQuery(query);

            if (rs.next()) {
                tersedia.setText(String.valueOf(rs.getInt("tersedia")));
                menipis.setText(String.valueOf(rs.getInt("menipis")));
                habis.setText(String.valueOf(rs.getInt("habis")));
            }

            rs.close();
        } catch (Exception e) {
            System.err.println("Error loadCardData: " + e.getMessage());
        }
    }

    private void loadTableData() {
        try {
            String query =
                "SELECT mp.code, mp.product_name, s.stock, mv.vendor_name " +
                "FROM stock s " +
                "LEFT JOIN m_product mp ON mp.id = s.product_id " +
                "LEFT JOIN m_vendor mv ON mv.id = mp.vendor_id " +
                "ORDER BY s.stock ASC";

            rs = Koneksi.stm.executeQuery(query);

            String[] columns = {"Kode", "Nama Produk", "Stok", "Vendor"};
            DefaultTableModel model = new DefaultTableModel(columns, 0);
            monitorstok_table.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30)
            );

            monitorstok_table.getTableHeader().setPreferredSize(
                new java.awt.Dimension(0, 40)
            );
            
            DefaultTableCellRenderer centerRenderer = (DefaultTableCellRenderer)
            monitorstok_table.getTableHeader().getDefaultRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);

            while (rs.next()) {
                Object[] row = {
                    rs.getString("code"),
                    rs.getString("product_name"),
                    rs.getInt("stock"),
                    rs.getString("vendor_name")
                };
                model.addRow(row);
            }

            monitorstok_table.setModel(model);
            rs.close();
        } catch (Exception e) {
            System.err.println("Error loadTableData: " + e.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tersedia = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        habis = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menipis = new javax.swing.JTextField();
        inventoripage_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        monitorstok_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel1.setText("MONITORING STOK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 690, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 80, 80));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TERSEDIA");

        tersedia.setBackground(new java.awt.Color(204, 204, 204));
        tersedia.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        tersedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tersedia.setToolTipText("");
        tersedia.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(tersedia, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(165, 165, 165))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tersedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel5.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HABIS");

        habis.setBackground(new java.awt.Color(204, 204, 204));
        habis.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        habis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        habis.setToolTipText("");
        habis.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(habis, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(165, 165, 165))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(habis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MENIPIS");

        menipis.setBackground(new java.awt.Color(204, 204, 204));
        menipis.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        menipis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        menipis.setToolTipText("");
        menipis.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(menipis, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(165, 165, 165))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(menipis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel5.add(jPanel7);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 1770, 250));

        inventoripage_button.setBackground(new java.awt.Color(153, 153, 153));
        inventoripage_button.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        inventoripage_button.setText("Manajemen Stok");
        inventoripage_button.setBorder(null);
        inventoripage_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoripage_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(inventoripage_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 70, 310, 70));

        monitorstok_table.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        monitorstok_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        monitorstok_table.setRowHeight(35);
        jScrollPane1.setViewportView(monitorstok_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 1770, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventoripage_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoripage_buttonActionPerformed
        // TODO add your handling code here:
        new ManajemenStok().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoripage_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorStok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField habis;
    private javax.swing.JButton inventoripage_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField menipis;
    private javax.swing.JTable monitorstok_table;
    private javax.swing.JTextField tersedia;
    // End of variables declaration//GEN-END:variables
}
